// Mocks generated by Mockito 5.4.6 from annotations
// in notes_app/test/features/notes/presentation/bloc/note_detail_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:notes_app/core/error/failures.dart' as _i6;
import 'package:notes_app/features/notes/domain/entities/note.dart' as _i7;
import 'package:notes_app/features/notes/domain/repositories/note_repository.dart'
    as _i2;
import 'package:notes_app/features/notes/domain/usecases/create_note.dart'
    as _i8;
import 'package:notes_app/features/notes/domain/usecases/delete_note.dart'
    as _i10;
import 'package:notes_app/features/notes/domain/usecases/get_note_by_id.dart'
    as _i4;
import 'package:notes_app/features/notes/domain/usecases/update_note.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNoteRepository_0 extends _i1.SmartFake
    implements _i2.NoteRepository {
  _FakeNoteRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetNoteById].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNoteById extends _i1.Mock implements _i4.GetNoteById {
  MockGetNoteById() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NoteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> call(_i4.NoteParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
              _FakeEither_1<_i6.Failure, _i7.Note>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);
}

/// A class which mocks [CreateNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateNote extends _i1.Mock implements _i8.CreateNote {
  MockCreateNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NoteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> call(_i8.NoteParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
              _FakeEither_1<_i6.Failure, _i7.Note>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);
}

/// A class which mocks [UpdateNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateNote extends _i1.Mock implements _i9.UpdateNote {
  MockUpdateNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NoteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> call(_i9.NoteParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
              _FakeEither_1<_i6.Failure, _i7.Note>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);
}

/// A class which mocks [DeleteNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteNote extends _i1.Mock implements _i10.DeleteNote {
  MockDeleteNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NoteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i10.NoteParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
