// Mocks generated by Mockito 5.4.6 from annotations
// in notes_app/test/features/notes/domain/usecases/get_notes_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:notes_app/core/error/failures.dart' as _i5;
import 'package:notes_app/features/notes/domain/entities/note.dart' as _i6;
import 'package:notes_app/features/notes/domain/repositories/note_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteRepository extends _i1.Mock implements _i3.NoteRepository {
  MockNoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>> getNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getNotes, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Note>>(
                    this,
                    Invocation.method(#getNotes, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>> searchNotes(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchNotes, [query]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Note>>(
                    this,
                    Invocation.method(#searchNotes, [query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Note>> getNoteById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteById, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>.value(
              _FakeEither_0<_i5.Failure, _i6.Note>(
                this,
                Invocation.method(#getNoteById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Note>> createNote(_i6.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [note]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>.value(
              _FakeEither_0<_i5.Failure, _i6.Note>(
                this,
                Invocation.method(#createNote, [note]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Note>> updateNote(_i6.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>.value(
              _FakeEither_0<_i5.Failure, _i6.Note>(
                this,
                Invocation.method(#updateNote, [note]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteNote(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteNote, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
